[package]
name = "verybad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
tempfile = "3.3.0"
rocket-client-addr = "0.5.1"
